# Generated by Django 3.2.16 on 2023-05-30 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hustlers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
