# Generated by Django 3.2.16 on 2023-02-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hustlers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerhustler',
            name='hustler_email_field',
            field=models.EmailField(default='SOME STRING', max_length=254),
        ),
        migrations.AddField(
            model_name='registerrecruiter',
            name='recruiter_email_field',
            field=models.EmailField(default='SOME STRING', max_length=254),
        ),
    ]
