# Generated by Django 3.2.16 on 2023-05-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hustlers', '0002_auto_20230207_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answers', models.JSONField()),
                ('correct_ans', models.CharField(max_length=255)),
            ],
        ),
    ]
