# Generated by Django 3.2.16 on 2023-05-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hustlers', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=6)),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='user',
            name='last_activity_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
