# Generated by Django 3.2.16 on 2023-05-23 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hustlers', '0005_auto_20230523_0119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
