# Generated by Django 3.2.16 on 2023-05-26 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hustlers', '0007_question_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='level',
        ),
    ]
