# Generated by Django 3.2.16 on 2023-05-26 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hustlers', '0009_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
