# Generated by Django 3.2.10 on 2023-07-05 19:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('competition_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('competition', models.CharField(max_length=150)),
                ('time', models.TimeField(default=None)),
                ('room_time', models.TimeField(default=None, null=True)),
            ],
        ),
    ]
