# Generated by Django 3.2.10 on 2023-07-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='room_time',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
