# Generated by Django 3.2.10 on 2023-07-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competion', '0003_alter_competition_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='left_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competition',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
