# Generated by Django 3.2.16 on 2023-07-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competion', '0004_auto_20230711_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='time',
            field=models.DateTimeField(default=None),
        ),
    ]
