# Generated by Django 3.2.10 on 2023-07-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competion', '0005_alter_competition_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='time',
            field=models.CharField(default=None, max_length=19),
        ),
    ]
