# Generated by Django 3.2.10 on 2023-07-10 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participant_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('Score', models.DecimalField(decimal_places=8, default=0.0, max_digits=100)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competion.competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('match_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('competition', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='competion.competition')),
                ('participant1', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant1', to='user.participant')),
                ('participant2', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant2', to='user.participant')),
                ('winner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='user.participant')),
            ],
        ),
    ]
