# Generated by Django 3.2.10 on 2023-07-06 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_permission',
        ),
    ]
