# Generated by Django 3.2.10 on 2023-07-11 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pair',
            name='participant1',
        ),
        migrations.RemoveField(
            model_name='pair',
            name='participant2',
        ),
        migrations.AddField(
            model_name='pair',
            name='opponent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to='user.participant'),
        ),
        migrations.AddField(
            model_name='pair',
            name='player',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='user.participant'),
        ),
    ]
