# Generated by Django 3.2.16 on 2023-08-01 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pair',
            name='participant1',
        ),
        migrations.RemoveField(
            model_name='pair',
            name='participant2',
        ),
        migrations.AddField(
            model_name='pair',
            name='creation_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pair',
            name='opponent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to='user.participant'),
        ),
        migrations.AddField(
            model_name='pair',
            name='player',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='user.participant'),
        ),
        migrations.AlterField(
            model_name='pair',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='user.participant'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='Score',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
