# Generated by Django 3.2.10 on 2023-07-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='Score',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=100),
        ),
    ]
