# Generated by Django 3.2.10 on 2023-07-06 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_delete_user_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='participant1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant1', to='user.participant'),
        ),
        migrations.AlterField(
            model_name='pair',
            name='participant2',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
