# Generated by Django 3.2.16 on 2023-08-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20230801_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='creation_date_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
