# Generated by Django 3.2.16 on 2023-07-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_participant_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
