# Generated by Django 3.2.10 on 2023-07-06 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20230706_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='participant2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant2', to='user.participant'),
        ),
    ]
