# Generated by Django 3.2.16 on 2023-08-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_pair_creation_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
