# Generated by Django 3.2.16 on 2023-07-15 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_participant_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='winner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='user.participant'),
        ),
    ]
