# Generated by Django 3.2.16 on 2023-07-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_pair_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
