# Generated by Django 3.2.16 on 2023-07-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_pair_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='Score',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=100),
        ),
    ]
